apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Tristan\Documents\INFS3208\project\infs3208\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Tristan\Documents\INFS3208\project\infs3208\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/mynet: "true"
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - npm
            - start
          image: backend
          name: backend
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: backend-claim0
            - mountPath: /node_modules
              name: backend-claim1
      restartPolicy: Always
      volumes:
        - name: backend-claim0
          persistentVolumeClaim:
            claimName: backend-claim0
        - name: backend-claim1
          persistentVolumeClaim:
            claimName: backend-claim1
status: {}
