version: "3.3"

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: ./db/database.sql
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet

  phpMyAdmin:
    image: phpmyadmin:latest
    container_name: phpMyAdmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    networks:
      - mynet

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
  backedn:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "9000:80"
networks:
  mynet:
    driver: bridge