apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Tristan\Documents\INFS3208\project\infs3208\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Tristan\Documents\INFS3208\project\infs3208\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/mynet: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: calendario
            - name: MYSQL_PASSWORD
              value: php
            - name: MYSQL_ROOT_PASSWORD
              value: MyDBRoot123
            - name: MYSQL_USER
              value: php
          image: mariadb:latest
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: maria-data
      restartPolicy: Always
      volumes:
        - name: maria-data
          persistentVolumeClaim:
            claimName: maria-data
status: {}
